### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by geeksailor** [digitalsleuth/peepdf-3#15]
@digitalsleuth Hey buddy! Sorry but found some weird issue when looking at two phishing emails I came across and thought I would throw them your way to see what you could make of it.
> [!] Error: An error has occurred while parsing an indirect object: 12 0 obj ([!] Error creating PDFStream: [!] Error analysing Javascript: SyntaxError: Invalid or unexpected token (  @ 1 : 4 )  -> OTTO)

Here are the files (zipped and password encoded to be safe. Password is infected.) Also, this error only happens on these files so it might just be a corrupt file or poorly written but wanted to be sure. It is a pretty crappy looking pdf so might just be someone not experienced with making pdf files and screwed up the JS.
[errorfiles.zip](https://github.com/digitalsleuth/peepdf-3/files/13966237/errorfiles.zip)

EDIT: I am still able to continue on and still analyze them using Peepdf-3 using the -f switch so this issue does not create a full stop on analysis.

**Comment by digitalsleuth** [comment]
Hi @geeksailor , this is actually intended behaviour, because JavaScript indicators were detected in the object and, while parsing the JS, the value of OTTO (which is at the start of the stream) not determined to not be a valid JS variable/object/token. The error you received (without the -f) lets you know that the JS in that object is not properly formatted and could not be analyzed or evaluated. 

Running with -f ignores the error at the outset, allows you to continue parsing, and stores the error it detected there in a file in your current directory named `jserror.log`. The errors you see are not errors with the application, but an error with how the JS is formed.

**Comment by geeksailor** [comment]
Glad it actually is nothing. Wanted to be sure though. Thanks for the follow up buddy. I'll close this and my other ticket out.
Cheers!
